version: "3.5"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - 3000:3000/tcp
    environment:
      - CONF=/api/conf.yaml
    networks:
      - status-check-network
  status_checker:
    container_name: status-check
    build:
      context: ./
    environment:
      - CONF=/status_check/conf.yaml
    command: bash /go/src/entrypoint.sh
    networks:
      - status-check-network
  postgres:
    image: postgres
    container_name: postgres-status-check
    volumes:
      - ./database/psql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - status-check-network
  kafka:
    image: landoop/fast-data-dev
    container_name: kafka_status_check
    networks:
      - status-check-network
  listener:
    container_name: status_listener
    build:
      context: .
      dockerfile: apps/status_listener/Dockerfile
    environment:
      - CONF=/status_listener/conf.yaml
    networks:
      - status-check-network
    depends_on:
      - kafka
      - postgres

networks:
  status-check-network:
    external:
      name: status-check-network