version: "3.5"

services:
  status-check:
    container_name: test-status-check
    build:
      context: ./
    ports:
      - 3001:3001/tcp
    environment:
      - CONF=/status_check/test/status_check.test.conf.yaml
    command: bash /go/src/entrypoint.sh
    depends_on:
      - postgres
      - fake-service
  fake-service:
    container_name: fake-services
    build:
      context: .
      dockerfile: fake_service/Dockerfile
    command: bash /go/src/entrypoint.sh
  postgres:
    image: postgres
    container_name: test-postgres-status-check
    ports:
      - 5432:5432/tcp
    volumes:
      - ./database/psql/init.sql:/docker-entrypoint-initdb.d/init.sql
